#!/bin/bash

# Vars and respective defaults
export CERBERUS_ENABLED=${CERBERUS_ENABLED:=False}
export CERBERUS_URL=${CERBERUS_URL:=http://0.0.0.0:8080}
export WAIT_DURATION=${WAIT_DURATION:=60}
export ITERATIONS=${ITERATIONS:=1}
export DAEMON_MODE=${DAEMON_MODE:=False}
export PUBLISH_KRAKEN_STATUS=${PUBLISH_KRAKEN_STATUS:=True}
export PORT=${PORT:=8081}
export LITMUS_VERSION=${LITMUS_VERSION:=v1.13.8}