# syntax=docker/dockerfile:1

FROM quay.io/sighup/kubectl-kustomize:1.21.6_3.9.1@sha256:ad6c3a96a2a2a7a19fc6fd0d43aba50bfe9ed4d0e944f8d0379190b213c1547b

LABEL krknctl.is_a_scenario="false"
LABEL krknctl.privileged="false"
LABEL krknctl.title="Kubectl Kustomize Workload"
LABEL krknctl.description="Pinned kubectl and kustomize helper image used by Krkn managed-cluster orchestration."
