# Dockerfile for cerberus in prow

FROM registry.ci.openshift.org/chaos/cerberus:latest as cerberus

LABEL maintainer="Red Hat Chaos Engineering Team"

# Install dependencies
RUN yum install -y which

# Copy configurations
ADD . /cerberus

RUN yum install -y python3 python3-pip python3-devel git diffutils gettext && \
    python3 -m pip install --upgrade pip

ENV PYTHONPATH=/cerberus/packages:$PYTHONPATH PYTHONUNBUFFERED=1

RUN ls

WORKDIR /cerberus