FROM quay.io/krkn-chaos/krkn:latest

# Global input fields (cerberus, telemetry, ES, health-checks, ...) are inherited
# from the krkn base image, so they don't need to be redeclared here.
COPY dummy-scenario/run.sh /home/krkn/run.sh

LABEL krknctl.is_a_scenario="true"
LABEL krknctl.privileged="false"
LABEL krknctl.has_rollback="true"
LABEL krknctl.kubeconfig_path="/home/krkn/.kube/config"
LABEL krknctl.title="Dummy Scenario"
LABEL krknctl.description="The dummy scenario simply waits for a specified amount of time without introducing any chaos. It serves as a root node in a flat graph structure to run multiple scenarios in parallel or can be used for testing purposes."

LABEL krknctl.input_fields='$KRKNCTL_INPUT'

ENTRYPOINT ["bash", "/home/krkn/run.sh"]